#!/usr/bin/env node
/**
 * build-mjs-cjs.js — bundle AWG-UIKIT-RACING JS modules into dist/awg-uikit.mjs and .cjs
 * No bundler dependency required (uses hand-written wrappers).
 * Author: AWGNET-RACING & AGENT AI TEAM
 */
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const dist = path.join(root, 'dist');
const jsDir = path.join(root, 'js');

const modules = [
  'awg-core.js',
  'awg-select2.js',
  'awg-charts.js',
  'awg-datatable.js',
  'awg-datepicker.js',
  'awg-widgets.js',
  'awg-maps.js',
];

const read = (file) => fs.readFileSync(path.join(jsDir, file), 'utf8');
const stripBanners = (src) => src.replace(/^\s*\/\*.*?\*\/\s*/s, '').replace(/^\s*\/\/.*$/gm, '');
const ensureEol = (src) => (/\n$/.test(src) ? src : src + '\n');

// Concatenate modules as-is (they all use IIFEs and assign window.* globals).
const shim = `
if (typeof document === 'undefined') {
  const __noop = () => ({ classList: { add(){}, remove(){} }, style: {}, dataset: {}, setAttribute(){}, appendChild(){}, addEventListener(){}, removeEventListener(){}, focus(){}, blur(){}, querySelector(){ return null; }, querySelectorAll(){ return []; }, closest(){ return null; }, getBoundingClientRect(){ return { left:0, top:0, right:0, bottom:0, width:0, height:0 }; }, contains(){ return false; } });
  class __doc {
    get documentElement() { return { dataset: {} }; }
    get body() { const b = __noop(); b.style = {}; b.removeChild = () => b; b.appendChild = () => b; return b; }
    get head() { return __noop(); }
    get activeElement() { return null; }
    get readyState() { return 'complete'; }
    addEventListener() {}
    removeEventListener() {}
    querySelector() { return null; }
    querySelectorAll() { return []; }
    getElementById() { return null; }
    createElement() { return __noop(); }
    createElementNS() { return __noop(); }
    createRange() { return null; }
    createTextNode() { return __noop(); }
    dispatchEvent() { return false; }
  }
  globalThis.document = new __doc();
}
if (typeof window === 'undefined') {
  globalThis.window = globalThis;
}
if (!globalThis.addEventListener) globalThis.addEventListener = function () {};
if (!globalThis.removeEventListener) globalThis.removeEventListener = function () {};
if (!globalThis.getComputedStyle) globalThis.getComputedStyle = () => ({ getPropertyValue: () => '' });
if (!globalThis.requestAnimationFrame) globalThis.requestAnimationFrame = (cb) => setTimeout(cb, 16);
if (!globalThis.cancelAnimationFrame) globalThis.cancelAnimationFrame = (id) => clearTimeout(id);
if (!globalThis.getSelection) globalThis.getSelection = () => null;
if (!globalThis.localStorage) globalThis.localStorage = { getItem: () => null, setItem: () => {}, removeItem: () => {} };
if (!globalThis.sessionStorage) globalThis.sessionStorage = globalThis.localStorage;
`;

const moduleBodies = [shim].concat(modules.map((m) => ensureEol(stripBanners(read(m)))));

const tailExports = `
const _Awg = (typeof globalThis !== 'undefined' && globalThis.Awg) || (typeof window !== 'undefined' && window.Awg) || null;
const _AwgSelect = (typeof globalThis !== 'undefined' && globalThis.AwgSelect) || (typeof window !== 'undefined' && window.AwgSelect) || null;
const _AwgChart = (typeof globalThis !== 'undefined' && globalThis.AwgChart) || (typeof window !== 'undefined' && window.AwgChart) || null;
const _AwgTable = (typeof globalThis !== 'undefined' && globalThis.AwgTable) || (typeof window !== 'undefined' && window.AwgTable) || null;
const _AwgDate = (typeof globalThis !== 'undefined' && globalThis.AwgDate) || (typeof window !== 'undefined' && window.AwgDate) || null;
const _AwgWizard = (typeof globalThis !== 'undefined' && globalThis.AwgWizard) || (typeof window !== 'undefined' && window.AwgWizard) || null;
const _AwgTree = (typeof globalThis !== 'undefined' && globalThis.AwgTree) || (typeof window !== 'undefined' && window.AwgTree) || null;
const _AwgPalette = (typeof globalThis !== 'undefined' && globalThis.AwgPalette) || (typeof window !== 'undefined' && window.AwgPalette) || null;
const _AwgKanban = (typeof globalThis !== 'undefined' && globalThis.AwgKanban) || (typeof window !== 'undefined' && window.AwgKanban) || null;
const _AwgLightbox = (typeof globalThis !== 'undefined' && globalThis.AwgLightbox) || (typeof window !== 'undefined' && window.AwgLightbox) || null;
const _AwgMap = (typeof globalThis !== 'undefined' && globalThis.AwgMap) || (typeof window !== 'undefined' && window.AwgMap) || null;
const _AwgToast = _Awg ? _Awg.toast : null;
const _AwgConfirm = _Awg ? _Awg.confirm : null;
`;

const esm = `// AWG-UIKIT-RACING ESM bundle — generated by scripts/build-mjs-cjs.js
// Author: AWGNET-RACING & AGENT AI TEAM
${moduleBodies.join('\n')}
${tailExports}
export {
  _Awg as Awg,
  _AwgSelect as AwgSelect,
  _AwgChart as AwgChart,
  _AwgTable as AwgTable,
  _AwgDate as AwgDate,
  _AwgWizard as AwgWizard,
  _AwgTree as AwgTree,
  _AwgPalette as AwgPalette,
  _AwgKanban as AwgKanban,
  _AwgLightbox as AwgLightbox,
  _AwgMap as AwgMap,
  _AwgToast as AwgToast,
  _AwgConfirm as AwgConfirm,
};
const AwgUIKit = {
  Awg: _Awg,
  AwgSelect: _AwgSelect,
  AwgChart: _AwgChart,
  AwgTable: _AwgTable,
  AwgDate: _AwgDate,
  AwgWizard: _AwgWizard,
  AwgTree: _AwgTree,
  AwgPalette: _AwgPalette,
  AwgKanban: _AwgKanban,
  AwgLightbox: _AwgLightbox,
  AwgMap: _AwgMap,
  AwgToast: _AwgToast,
  AwgConfirm: _AwgConfirm,
};
export default AwgUIKit;
`;

const cjs = `// AWG-UIKIT-RACING CJS bundle — generated by scripts/build-mjs-cjs.js
// Author: AWGNET-RACING & AGENT AI TEAM
${moduleBodies.join('\n')}
${tailExports}
if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    Awg: _Awg,
    AwgSelect: _AwgSelect,
    AwgChart: _AwgChart,
    AwgTable: _AwgTable,
    AwgDate: _AwgDate,
    AwgWizard: _AwgWizard,
    AwgTree: _AwgTree,
    AwgPalette: _AwgPalette,
    AwgKanban: _AwgKanban,
    AwgLightbox: _AwgLightbox,
    AwgMap: _AwgMap,
    AwgToast: _AwgToast,
    AwgConfirm: _AwgConfirm,
    default: {
      Awg: _Awg,
      AwgSelect: _AwgSelect,
      AwgChart: _AwgChart,
      AwgTable: _AwgTable,
      AwgDate: _AwgDate,
      AwgWizard: _AwgWizard,
      AwgTree: _AwgTree,
      AwgPalette: _AwgPalette,
      AwgKanban: _AwgKanban,
      AwgLightbox: _AwgLightbox,
      AwgMap: _AwgMap,
      AwgToast: _AwgToast,
      AwgConfirm: _AwgConfirm,
    },
  };
}
`;

fs.mkdirSync(dist, { recursive: true });
fs.writeFileSync(path.join(dist, 'awg-uikit.mjs'), esm);
fs.writeFileSync(path.join(dist, 'awg-uikit.cjs'), cjs);

const size = (f) => fs.statSync(path.join(dist, f)).size;
console.log('Generated:');
console.log('  dist/awg-uikit.mjs', size('awg-uikit.mjs'), 'bytes');
console.log('  dist/awg-uikit.cjs', size('awg-uikit.cjs'), 'bytes');
